# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rec',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.User'),
        ),
    ]
