# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20170106_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='api',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
